/**
 * Figma DS file creation from extracted tokens.
 *
 * brand-capture runs in a terminal. Figma MCP runs inside Claude.
 * They can't talk to each other from a subprocess.
 *
 * So: brand-capture generates TWO ready-to-use files:
 *   1. figma-setup.js   — the use_figma code (variables, pages, collections)
 *   2. figma-prompt.md  — a copy-paste-ready prompt for Claude
 *
 * The user either:
 *   A. Is already in a Claude session → says "run brand-to-figma for <brand>"
 *      and Claude reads figma-setup.js and runs it via Figma MCP
 *   B. Opens a new Claude session → pastes figma-prompt.md → done
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateFigmaSetupScript } from "./generate-setup-script.js";
import type { CKMap } from "../types.js";

export interface FigmaCreateResult {
  setupScriptPath: string;
  promptPath: string;
}

export async function autoCreateFigmaDS(
  brandName: string,
  ckMap: CKMap,
  outDir: string
): Promise<FigmaCreateResult> {
  const setupScript = generateFigmaSetupScript(brandName, ckMap);
  const scriptPath = join(outDir, "figma-setup.js");
  writeFileSync(scriptPath, setupScript, "utf8");

  const promptPath = join(outDir, "figma-prompt.md");
  const prompt = buildPrompt(brandName, scriptPath, setupScript);
  writeFileSync(promptPath, prompt, "utf8");

  console.log(`
  ✓ Figma setup script generated: ${scriptPath}
  ✓ Claude prompt generated:      ${promptPath}

  ── To create the Figma DS file ──────────────────────────────
  You need a Claude session with Figma MCP connected. Then either:

  Option A — If you're already in Claude:
    Tell Claude: "Read ${scriptPath} and create a new Figma file
    called '${brandName} — Design System', then run the setup script in it"

  Option B — Copy the prompt:
    cat ${promptPath} | pbcopy
    → paste into any Claude conversation with Figma MCP

  Option C — Claude Code CLI (if in the design-os workspace):
    /ds build --brand ${brandName}
  `);

  return { setupScriptPath: scriptPath, promptPath };
}

function buildPrompt(brandName: string, scriptPath: string, script: string): string {
  return `# Create Figma Design System: ${brandName}

Do these steps in order. You need Figma MCP connected.

## Step 1 — Create a new Figma file

Use \`create_new_file\` to create a design file named **"${brandName} — Design System"**.
Use the user's team (run \`whoami\` first to get the plan key).

## Step 2 — Run the setup script

Use \`use_figma\` on the new file with this code:

\`\`\`javascript
${script}
\`\`\`

## Step 3 — Confirm

Take a screenshot of the Variables panel and return the file URL.

---
*Generated by brand-capture from ${scriptPath}*
`;
}
