/**
 * Generates the use_figma JavaScript to run inside a new Figma file.
 * Takes a CKMap (from collectivekit-mapper) and produces:
 *   - Page setup (◘ 00 Variables, ◘ 01 Components, ◘ 02 Templates)
 *   - Variable collections (primitives, semantic Light+Dark, spacing, radius)
 *   - All variable values from the extraction
 */

import type { CKMap } from "../types.js";

export function generateFigmaSetupScript(brandName: string, ckMap: CKMap): string {
  const { colors, typography, borders } = ckMap;

  // Convert hex to 0-1 RGB
  function hexToRgb(hex: string): string {
    const h = hex.replace("#", "");
    const r = (parseInt(h.slice(0, 2), 16) / 255).toFixed(4);
    const g = (parseInt(h.slice(2, 4), 16) / 255).toFixed(4);
    const b = (parseInt(h.slice(4, 6), 16) / 255).toFixed(4);
    return `{r:${r},g:${g},b:${b}}`;
  }

  // Build semantic variable entries from the CK map
  const semanticEntries = Object.entries(colors)
    .filter(([, hex]) => hex && hex.startsWith("#"))
    .map(([slot, hex]) => {
      const scope = slot.startsWith("surface") ? "['FRAME_FILL','SHAPE_FILL']"
        : slot.startsWith("text") ? "['TEXT_FILL']"
        : slot.startsWith("border") ? "['STROKE_COLOR']"
        : "['FRAME_FILL','SHAPE_FILL']";
      return `  { name:${JSON.stringify(slot)}, light:${hexToRgb(hex)}, dark:${hexToRgb(hex)}, scope:${scope} }`;
    });

  // Derive dark-mode inverses: dark surfaces flip to near-black, light text flips to near-white
  // (Simple heuristic — designer refines in Figma)
  const darkInverses: Record<string, string> = {};
  for (const [slot, hex] of Object.entries(colors)) {
    if (!hex || !hex.startsWith("#")) continue;
    const l = getLightness(hex);
    if (slot.startsWith("surface") && l > 80) {
      darkInverses[slot] = "#121212"; // light surface → dark bg
    } else if (slot.startsWith("surface") && l < 20) {
      darkInverses[slot] = "#1a1a2e"; // dark surface → stays dark
    } else if (slot.startsWith("text") && l < 30) {
      darkInverses[slot] = "#f0f0f0"; // dark text → light text
    }
  }

  const semanticWithDark = Object.entries(colors)
    .filter(([, hex]) => hex && hex.startsWith("#"))
    .map(([slot, hex]) => {
      const dark = darkInverses[slot] ?? hex;
      const scope = slot.startsWith("surface") ? "['FRAME_FILL','SHAPE_FILL']"
        : slot.startsWith("text") ? "['TEXT_FILL']"
        : slot.startsWith("border") ? "['STROKE_COLOR']"
        : "['FRAME_FILL','SHAPE_FILL']";
      return `  { name:${JSON.stringify(slot)}, light:${hexToRgb(hex)}, dark:${hexToRgb(dark)}, scope:${scope} }`;
    });

  const typeScaleEntries = Object.entries(typography.scale)
    .map(([slot, val]) => `  { name:${JSON.stringify(slot)}, value:${val} }`);

  const borderEntries = Object.entries(borders)
    .map(([slot, val]) => `  { name:${JSON.stringify(slot)}, value:${val} }`);

  return `
// ── Generated by brand-capture for: ${brandName} ──────────────────────────
// Run this via use_figma in a new Figma file.
// Creates pages, variable collections, and all brand variables.

// ── Pages ────────────────────────────────────────────────────────────────────
const defaultPage = figma.root.children[0];
defaultPage.name = '◘ 00 Variables';
const compPage = figma.createPage(); compPage.name = '◘ 01 Components';
const tmplPage = figma.createPage(); tmplPage.name = '◘ 02 Templates';
await figma.setCurrentPageAsync(defaultPage);

// ── Collections ──────────────────────────────────────────────────────────────
const primColl = figma.variables.createVariableCollection('primitives');
primColl.modes[0].name = 'Value';

const semColl = figma.variables.createVariableCollection('semantic');
semColl.modes[0].name = 'Light';
const darkModeId = semColl.addMode('Dark');
const lightModeId = semColl.modes[0].modeId;

const spaceColl = figma.variables.createVariableCollection('spacing');
spaceColl.modes[0].name = 'Value';
const spaceMode = spaceColl.modes[0].modeId;

const radColl = figma.variables.createVariableCollection('radius');
radColl.modes[0].name = 'Value';
const radMode = radColl.modes[0].modeId;

// ── Spacing scale (base 4px) ─────────────────────────────────────────────────
const SPACING = [
  {name:'space/1',value:4},{name:'space/2',value:8},{name:'space/3',value:12},
  {name:'space/4',value:16},{name:'space/5',value:20},{name:'space/6',value:24},
  {name:'space/8',value:32},{name:'space/10',value:40},{name:'space/12',value:48},
  {name:'space/16',value:64},{name:'space/20',value:80},{name:'space/24',value:96},
];
for (const s of SPACING) {
  const v = figma.variables.createVariable(s.name, spaceColl, 'FLOAT');
  v.scopes = ['GAP','WIDTH_HEIGHT'];
  v.setValueForMode(spaceMode, s.value);
}

// ── Radius scale ─────────────────────────────────────────────────────────────
const RADIUS = [
  {name:'radius/none',value:0},{name:'radius/sm',value:4},{name:'radius/md',value:8},
  {name:'radius/lg',value:12},{name:'radius/xl',value:16},{name:'radius/2xl',value:24},
  {name:'radius/full',value:9999},
];
for (const r of RADIUS) {
  const v = figma.variables.createVariable(r.name, radColl, 'FLOAT');
  v.scopes = ['CORNER_RADIUS'];
  v.setValueForMode(radMode, r.value);
}

// ── Typography ────────────────────────────────────────────────────────────────
const typoColl = figma.variables.createVariableCollection('typography');
typoColl.modes[0].name = 'Value';
const typoMode = typoColl.modes[0].modeId;

const TYPO_SCALE = [
${typeScaleEntries.join(",\n")}
];
for (const t of TYPO_SCALE) {
  const v = figma.variables.createVariable(t.name, typoColl, 'FLOAT');
  v.scopes = ['FONT_SIZE','LINE_HEIGHT'];
  v.setValueForMode(typoMode, t.value);
}

// Font families
const headingFontVar = figma.variables.createVariable('font/heading', typoColl, 'STRING');
headingFontVar.setValueForMode(typoMode, ${JSON.stringify(typography.headingFamily)});
const bodyFontVar = figma.variables.createVariable('font/body', typoColl, 'STRING');
bodyFontVar.setValueForMode(typoMode, ${JSON.stringify(typography.paragraphFamily)});

// ── Border widths ─────────────────────────────────────────────────────────────
const BORDERS = [
${borderEntries.join(",\n")}
];
for (const b of BORDERS) {
  const v = figma.variables.createVariable(b.name, spaceColl, 'FLOAT');
  v.scopes = ['STROKE_FLOAT'];
  v.setValueForMode(spaceMode, b.value);
}

// ── Semantic colors (brand-specific — Light + Dark) ───────────────────────────
const SEMANTIC = [
${semanticWithDark.join(",\n")}
];
for (const s of SEMANTIC) {
  const v = figma.variables.createVariable(s.name, semColl, 'COLOR');
  v.scopes = s.scope;
  v.setValueForMode(lightModeId, s.light);
  v.setValueForMode(darkModeId, s.dark);
}

return {
  fileKey: figma.root.id,
  pages: figma.root.children.map(p => p.name),
  collections: (await figma.variables.getLocalVariableCollectionsAsync()).map(c => ({
    name: c.name,
    count: c.variableIds.length,
    modes: c.modes.map(m => m.name)
  }))
};
`.trim();
}

function getLightness(hex: string): number {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  return ((Math.max(r, g, b) + Math.min(r, g, b)) / 2) * 100;
}
